version: "3.8"

services:
  web:
    build: ./apps/web
    container_name: web
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  api:
    build: ./apps/api
    container_name: api
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - ENV=production

  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api

volumes:
  db_data:
