version: "3.8"

services:
  web:
    build: ./apps/web
    container_name: web
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL:-/api}

  api:
    build: ./apps/api
    container_name: api
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - ENV=${ENV:-Development}

  db:
    image: postgres:16
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - web
      - api

volumes:
  db_data:
