[package]
name = "mongo_backup"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "process", "signal"] }
tokio-cron-scheduler = "0.9"
chrono = { version = "0.4", features = ["clock"] }
anyhow = "1"
